### ISSUE TITLE
Error seen with running staged_score() heuristic

### ISSUE THREAD

**Issue by alikureishy** [safdark/isolation#1]
Playing Matches:
----------
  Match 1: ID_staged_score vs   Random    Traceback (most recent call last):
  File "tournament.py", line 199, in <module>
    main()
  File "tournament.py", line 191, in main
    win_ratio = play_round(agents, NUM_MATCHES)
  File "tournament.py", line 131, in play_round
    score_1, score_2 = play_match(p1, p2)
  File "tournament.py", line 86, in play_match
    winner, _, termination = game.play(time_limit=TIME_LIMIT)
  File "/Users/safdar/Documents/aind/isolation/isolation/isolation.py", line 338, in play
    curr_move = self.active_player.get_move(game_copy, legal_player_moves, time_left)
  File "/Users/safdar/Documents/aind/isolation/game_agent.py", line 125, in get_move
    assert not (move is None or move is (-1,-1)), "Move ({}, {}) for '{}/{}' cannot be None or (-1,-1) if options ({}) exist".format(move, score, self.method, self.score_fn, options)

**Comment by alikureishy** [comment]
The issue only occurs with this heuristic:

def staged_score(game, player):
    # Strategy:
    # - First half: Stay near center + stay away from other
    # - Second half: Stay close + offensive + net_mobility
    # - Third half: net_advantage
    stage = game_stage(game)
    if stage <= 33.0:
        return combo_nearcenter_avoidopponent_score(game, player)
    elif stage <= 66.0:
        return combo_offensive_nearopponent_netmobility_score(game, player)
    else:
        return combo_netadvantage_nearopponent_score(game, player)

.... but the issue is with the alphabeta() search. Not sure if minimax() has an issue. Check through tournament.py.

**Comment by alikureishy** [comment]
Fixed in branch issue1. Merged back to master.
